%% FireFly Commands Description
clc;

fprintf('\n\n========================================================');
fprintf('\nRequest/response command description:\nwith this message you can request data from a node\nand you will get sensor data as return once\n\nin the inject node below first 3 places are ID\nof the node you want data from,\nfourth is the command number request/response is command 0\n\nso message structure for FF-K12 node would be\nK120\n');
fprintf('\n\n========================================================');
fprintf('\nContinous response command description:\nwith this message you can request data from a node\nand you will get sensor data as return continuously\nwith interval you''ve written\n\nin the inject node below first 3 places are ID\nof the node you want data from,\nfourth is the command number request/response is command 1\n\nfifth is what unit of measurement you want:\n    4 meaning miliseconds\n    3 meaning seconds\n    2 meaning minutes\n    1 meaning hours\n\nand the last 2 are the time in meaning\n05 would mean 5 units of measurement\n\nand 305 at the end would mean 5 seconds\n\nso message structure for FF-K12 node would be\nK121305\nwhich means node K12 will respond every 5 seconds\n');
fprintf('\n\n========================================================');
fprintf('\nTurn on/off sensors command description:\nwith this message you can turn on/off sensors on a node\n\nopen function node set sensors ON/OFF\nin which you will see described in comments which parameters you can change\n\nNOTE here, if the value you select here specifies only humidity sensor\nto be turned on, any other sensor that is currently turned on, will be turned off when\nyou send this command\n');
fprintf('\n\n========================================================');
fprintf('\nKill continuous response command description:\nwith this message you can kill continuous response you''ve started \nwith command 1\n\nin the inject node below first 3 places are ID\nof the node you want data from,¸\nfourth is the command number kill continuous response is command 2\n\nso message structure for FF-K12 node would be\nK122\n');
fprintf('\n\n========================================================');
fprintf('\nSet outputs command description:\nOpen function node called \"set outputs\"\nparameters you can change are:\n\nnode\nLED1 //turns LED1 ON or OFF\nLED2 //turns LED2 ON or OFF\nLED3 //turns LED3 ON or OFF\np0_15 //writes value to pin p0-15\np0_27 //writes value to pin p0-27\n');
fprintf('\n\n========================================================');
fprintf('\nSet sensors ON/OFF:\n/*NOTE here, if the value you select here specifies only humidity sensor\nto be turned on, any other sensor that is currently turned on, will be turned off when\nyou send this command*/\n\nvar node = \"K12\";  //this is the node the command is being sent to\n\nvar lux     = 1; // set to 1 if you want sensor to be on 0 for it to be off\nvar Rh      = 1; // set to 1 if you want sensor to be on 0 for it to be off\nvar temp    = 1; // set to 1 if you want sensor to be on 0 for it to be off\nvar mag     = 1; // set to 1 if you want sensor to be on 0 for it to be off\nvar accel   = 1; // set to 1 if you want sensor to be on 0 for it to be off\nvar gyro    = 1; // set to 1 if you want sensor to be on 0 for it to be off\n\nvar sensors;\n\nsensors = sensors  | (lux   << 0);\nsensors = sensors  | (Rh    << 1);\nsensors = sensors  | (temp  << 2);\nsensors =  sensors | (mag   << 3);\nsensors = sensors  | (accel << 4);\nsensors = sensors  | (gyro  << 5);\nsensors = sensors  | (1  << 6);\n\nvar char = String.fromCharCode(sensors);\n\nmsg.payload = \"{\\\"cmd\\\":\\\"\" + node + \"4\" + char + \"\\\"}\";\nreturn msg;\n');
fprintf('\n\n========================================================');
fprintf('\nSet outputs:\nvar node = \"K12\";  //this is the node the command is being sent to\n                  //if the node is called FF-K12 only write K12\n\nvar LED1    = 0; // set to 0 if you want LED1 to be on 1 for it to be off\nvar LED2    = 0; // set to 0 if you want LED2 to be on 1 for it to be off\nvar LED3    = 0; // set to 0 if you want LED3 to be on 1 for it to be off\nvar p0_15   = 0; // set to 1 if you want output p0_15 to be on 0 for it to be off\nvar p0_27   = 0; // set to 1 if you want output p0_27 to be on 0 for it to be off\n\nvar output;\n\noutput = output  | (LED1   << 0);\noutput = output  | (LED2   << 1);\noutput = output  | (LED3   << 2);\noutput = output  | (p0_15  << 3);\noutput = output  | (p0_27  << 4);\noutput = output  | (1  << 6);\n\n\n//var char = String.fromCharCode(output + 33);\nvar char = String.fromCharCode(output);\n\nmsg.payload = \"{\\\"cmd\\\":\\\"\" + node + \"3\" + char + \"\\\"}\";\nreturn msg;\n//return char;\n');
